name: Build and Deploy Backend to Azure Web App (Docker + ACR)

on:
    push:
        branches:
            - chore/azure-config
    workflow_dispatch:

jobs:
    docker-deploy:
        runs-on: ubuntu-latest

        steps:
            # Checkout do reposit√≥rio
            - name: Checkout repository
              uses: actions/checkout@v4

            # Login na Azure
            - name: Azure Login
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            # Login no ACR
            - name: Login to Azure Container Registry
              uses: azure/docker-login@v1
              with:
                  login-server: twentbackendacr.azurecr.io
                  username: ${{ secrets.AZURE_ACR_USERNAME }}
                  password: ${{ secrets.AZURE_ACR_PASSWORD }}

            # Build da imagem Docker usando o Dockerfile dentro de /backend
            - name: Build Docker image
              run: |
                  docker build -t twentbackendacr.azurecr.io/twent-backend:latest ./backend

            # Push da imagem para o ACR
            - name: Push Docker image
              run: |
                  docker push twentbackendacr.azurecr.io/twent-backend:latest

            # Deploy no Azure Web App for Containers
            - name: Deploy image to Azure Web App
              uses: azure/webapps-deploy@v3
              with:
                  app-name: 'twent-backend'
                  slot-name: 'Production'
                  images: 'twentbackendacr.azurecr.io/twent-backend:latest'
