name: Build and deploy Node.js app to Azure Web App - twent-backend

on:
    push:
        branches:
            - chore/azure-config
    workflow_dispatch:

jobs:
    docker-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Login to Azure
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Login to Azure Container Registry
              uses: azure/docker-login@v1
              with:
                  login-server: twentbackendacr.azurecr.io
                  username: ${{ secrets.AZURE_ACR_USERNAME }}
                  password: ${{ secrets.AZURE_ACR_PASSWORD }}

            - name: Build Docker image
              run: |
                  docker build -t twentbackendacr.azurecr.io/twent-backend:latest ./backend

            - name: Push Docker image
              run: |
                  docker push twentbackendacr.azurecr.io/twent-backend:latest

            - name: Deploy image to Azure Web App
              uses: azure/webapps-deploy@v3
              with:
                  app-name: 'twent-backend'
                  slot-name: 'Production'
                  images: 'twentbackendacr.azurecr.io/twent-backend:latest'
