name: Build and Deploy Backend to Azure Web App (Docker + ACR)

on:
    push:
        branches:
            - chore/azure-config
    workflow_dispatch:

jobs:
    docker-deploy:
        runs-on: ubuntu-latest

        steps:
            # Checkout do reposit√≥rio
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Login to Azure
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_344F33E0313E49458AEB101102DB56B6 }}
                  tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_29165FF121814D278BFDC67C0758988E }}
                  subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8C7F6669DE38463EA96B3DC81FA2CFC7 }}

            # Login no ACR
            - name: Login to Azure Container Registry
              uses: azure/docker-login@v1
              with:
                  login-server: ${{ secrets.ACR_LOGIN_SERVER }}
                  username: ${{ secrets.ACR_USERNAME }}
                  password: ${{ secrets.ACR_PASSWORD }}

            # Build da imagem Docker usando o Dockerfile dentro de /backend
            - name: Build Docker image
              run: |
                  docker build -t ${{secrets.ACR_LOGIN_SERVER}}/twent-backend:latest ./backend

            # Push da imagem para o ACR
            - name: Push Docker image
              run: |
                  docker push ${{secrets.ACR_LOGIN_SERVER}}/twent-backend:latest

            # Deploy no Azure Web App for Containers
            - name: Deploy image to Azure Web App
              uses: azure/webapps-deploy@v3
              with:
                  app-name: '${{secrets.AZURE_WEBAPP_NAME}}'
                  slot-name: 'Production'
                  images: '${{secrets.ACR_LOGIN_SERVER}}/twent-backend:latest'
